
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CMSFinal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class File
{

    public int Id { get; set; }

    public string FilePath { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> LastModifiedDate { get; set; }

    public Nullable<int> Ideaid { get; set; }



    public virtual Idea Idea { get; set; }

}

}
